version: "3"
services:
  cinemacharts:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data: