version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./build/:/www/data"
    ports:
      - "80:8080"
    depends_on:
      - cinemacharts
    restart: "always"
  cinemacharts:
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    expose:
      - "8080"
    depends_on:
      - mongo
    restart: "always"
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
    restart: "always"
volumes:
  mongo-data: