version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./build/:/www/data"
    ports:
      - "8080:8080"
    depends_on:
      - cinemacharts
  cinemacharts:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/cinemacharts"
    expose:
      - "8080"
    depends_on:
      - mongo
    command: "npm run dev"
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
volumes:
  mongo-data: